config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :courses do
    resources :weeks
  end

  resources :weeks do
    resources :lessons
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :weeks
  validates :name, :presence => true
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  belongs_to :week

  validates_presence_of :title, :body, :day, :lesson_type
end

app/models/week.rb
class Week < ActiveRecord::Base
  belongs_to :course
  has_many :lessons

  validates :name, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.all
  end

  def show
    @course = Course.find(params[:id])
  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.new(course_params)
    if @course.save
      flash[:notice] = "Course successfully added!"
      redirect_to courses_path
    else
      render :new
    end
  end

  def edit
    @course = Course.find(params[:id])
  end

  def update
    @course= Course.find(params[:id])
    if @course.update(course_params)
      flash[:notice] = "Edit Successful!"
      redirect_to courses_path
    else
      render :edit
    end
  end

  def destroy
    @course = Course.find(params[:id])
    @course.destroy
    redirect_to courses_path
  end

  private
  def course_params
    params.require(:course).permit(:name)
  end

end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  def index
    @lessons = Lesson.all
  end

  def show
    @week = Week.find(params[:week_id])
    @lesson = Lesson.find(params[:id])
  end

  def new
    @week = Week.find(params[:week_id])
    @lesson = @week.lessons.new
  end

  def create
    @week = Week.find(params[:week_id])
    @lesson = @week.lessons.new(lesson_params)
    if @lesson.save
      flash[:notice] = "Lesson successfully added!"
      redirect_to course_week_path(@week.course, @lesson.week)
    else
      render :new
    end
  end

  def edit
    @week = Week.find(params[:week_id])
    @lesson = Lesson.find(params[:id])
  end

  def update
    @week = Week.find(params[:week_id])
    @lesson= Lesson.find(params[:id])
    if @lesson.update(lesson_params)
      flash[:notice] = "Edit Successful!"
      redirect_to week_lesson_path(@week, @lesson)
    else
      render :edit
    end
  end

  def destroy
    @week = Week.find(params[:week_id])
    @lesson = Lesson.find(params[:id])
    @lesson.destroy
    redirect_to course_week_path(@week.course, @lesson.week)
  end

  private
  def lesson_params
    params.require(:lesson).permit(:title, :body, :day, :lesson_type)
  end

end

app/controllers/weeks_controller.rb
class WeeksController < ApplicationController
  def index
    @weeks = Week.all
  end

  def show
    @course = Course.find(params[:course_id])
    @week = Week.find(params[:id])
  end

  def new
    @course = Course.find(params[:course_id])
    @week = @course.weeks.new
  end

  def create
    @course = Course.find(params[:course_id])
    @week = @course.weeks.new(week_params)
    if @week.save
      flash[:notice] = "Week successfully added!"
      redirect_to course_path(@week.course)
    else
      render :new
    end
  end

  def edit
    @course = Course.find(params[:course_id])
    @week = Week.find(params[:id])
  end

  def update
    @course = Course.find(params[:course_id])
    @week= Week.find(params[:id])
    if @week.update(week_params)
      flash[:notice] = "Edit Successful!"
      redirect_to course_week_path(@course, @week)
    else
      render :edit
    end
  end

  def destroy
    @week = Week.find(params[:id])
    @week.destroy
    redirect_to course_path(@week.course)
  end

  private
  def week_params
    params.require(:week).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/courses/_form.html.erb
<%= render "layouts/errors", :object => @course %>

<%= form_for @course do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/courses/edit.html.erb
<h1>Edit Course</h1>

<%= render "form" %>

app/views/courses/index.html.erb
<% content_for(:title, "Courses") %>

<h1>Courses</h1>

<ul>
  <% @courses.each do |course| %>
    <li><%= link_to course.name, course_path(course)%></li>
  <% end %>
</ul>

<%= link_to "New Course", new_course_path %>

app/views/courses/new.html.erb
<% content_for(:title, "| New Course") %>


<h1>New Course</h1>

<%= render 'form' %>

app/views/courses/show.html.erb
<h1><%= @course.name %></h1>
<% @course.weeks.each do |week| %>
  <h3><%= link_to week.name, course_week_path(@course, week)%></h3>
<% end %>


<p><%= link_to "Add a Week", new_course_week_path(@course) %></p>

<p><%= link_to "Edit", edit_course_path(@course) %></p>
<p><%= link_to "Delete", course_path(@course), :data => {:confirm => "You sure?", :method => "delete"} %></p>



<%= link_to "Return to Courses", courses_path %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LearnHowToProgram</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= flash[:alert] %>
    <%= flash[:notice] %>
    <%= yield %>
  </body>
</html>

app/views/lessons/_form.html.erb
<%= render "layouts/errors", :object => @lesson %>

<%= form_for [@week, @lesson] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :day %>
  <%= f.text_field :day %>
  <%= f.label :lesson_type %>
  <%= f.text_field :lesson_type %>
  <%= f.label :body %>
  <%= f.text_area :body, size: "80x12" %>
  <%= f.submit %>
<% end %>

app/views/lessons/edit.html.erb
<h1>Edit Lesson</h1>

<%= render "form" %>

app/views/lessons/new.html.erb
<% content_for(:title, "| New Lesson") %>


<h1>New Lesson</h1>

<%= render 'form' %>

app/views/lessons/show.html.erb
<h1><%= @lesson.title %></h1>
<h3><%= @lesson.day %> | <%= @lesson.lesson_type %></h3>

<p><%= @lesson.body%></p>


<p><%= link_to "Edit", edit_week_lesson_path(@week) %></p>
<p><%= link_to "Delete", week_lesson_path(@week, @lesson), :data => {:confirm => "You sure?", :method => "delete"} %></p>



<%= link_to "Return to #{@lesson.week.name}", week_path(@lesson.week) %>

app/views/weeks/_form.html.erb
<%= render "layouts/errors", :object => @week %>

<%= form_for [@course, @week] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/weeks/edit.html.erb
<h1>Edit Week</h1>

<%= render "form" %>

app/views/weeks/new.html.erb
<% content_for(:title, "| New Week") %>


<h1>New Week</h1>

<%= render 'form' %>

app/views/weeks/show.html.erb
<h1><%= @week.name %></h1>
<% @week.lessons.each do |lesson| %>
  <h3><%= link_to lesson.title, week_lesson_path(@week, lesson)%></h3>
<% end %>


<p><%= link_to "Add a Lesson", new_week_lesson_path(@week) %></p>

<p><%= link_to "Edit", edit_course_week_path(@course) %></p>
<p><%= link_to "Delete", week_path(@week), :data => {:confirm => "You sure?", :method => "delete"} %></p>



<%= link_to "Return to #{@week.course.name}", course_path(@week.course) %>